name: schreibwerkstatt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.60658
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#313E60'
    - '#FFC8B7'
    - '#010001'
    - '#55889B'
  brandStrength: 1
  lightness: 0.9322368188295513
  saturation: 0.9896209568250924
  rhythmicContrast: 0.3808784633874893
purpose: []
